### PR TITLE
Fix annotation category and name filter

### PR DESCRIPTION
**Pull request by coderReview**

### CODE REVIEW

**Comment by ritchiecarroll** [comment]
FYI, I'm tempted just to merge this - I currently do not have an active instance of OSI-PI with the PI Web API running where I can test this.

What testing have you done on this PR?

**Comment by coderReview** [comment]
hi @ritchiecarroll we have been using this change for over 6 months without any problem.

**Comment by coderReview** [comment]
Thank @ritchiecarroll. Can you also publish to the grafana system so everyone can download?

**Comment by ritchiecarroll** [comment]
Check your e-mail associated with your GitHub account. You should have two invites for write access to this repo and grafana-plugin-repository. 

Pull latest updates on `grafana-plugin-repository` and add a new version for this repo update, then create a PR for grafana based on that update. Once Grafana staff approve, new update will be published.

**Comment by coderReview** [comment]
Ok @ritchiecarroll

**Pull request merged**
