### PR TITLE
Added a state in the query control so that the user can define if he expects string values.

### PR DESCRIPTION
**Pull request by imes-manuel**
Resolves Issue #34 Plug-in is incompatible with string data types

Also added the functionality to realize if a returned value is not good and then extracting the string value returned by PI (like Bad Value).
Also added an additional function for null value handling - Added Keep.
This works with AF values that return a fixed string as well as with pi point references of digital states points.

### CODE REVIEW

**Comment by jonaspolfliet** [comment]
Hi, small question about this 'Digital State' button.
I changed all the files like #45 is described but the button don't appear. Do I need to rebuild something to get this working?

Kind regards

**Comment by ritchiecarroll** [comment]
You will need to restart Grafana, then a hard refresh on the browser won't hurt.

**Comment by jonaspolfliet** [comment]
> You will need to restart Grafana, then a hard refresh on the browser won't hurt.

Nope, sorry in the explorer view of the query I don't see the digital state switch.

**Comment by ritchiecarroll** [comment]
> Nope, sorry in the explorer view of the query I don't see the digital state switch

OK, I'll have to let one of the maintainers weigh in. What do you see if press F12, any errors on the browser console?

**Comment by jonaspolfliet** [comment]
No errors in the console. Just warnings:
- Duplicate field names found: Value, only the first will be accessible
- Using strings as events is deprecated and will be removed in a future version.

**Comment by Coding-Mike** [comment]
When will this pull request be merged into the main branch and added to the official plugin on the grafana plugin page. We would really need the solution of this pull request.

Kind regards
Michael

**Comment by coderReview** [comment]
hi @ritchiecarroll  let me see if I can find this week to check. If not let's go ahead.

**Pull request merged**
