### PR TITLE
Pi point option in admin config page

### PR DESCRIPTION
**Pull request by TheFern2**
This takes care of #82, there's a new toggle button in the admin page. The reason for this change to is control access to pi points for certain users. Nothing else was changed, this is a pure ui change.

image

Which will hide the pi point toggle button in the query page:

image

Toggling to true will show the toggle in query page:

image

### CODE REVIEW

**Comment by coderReview** [comment]
I think it's a good idea to block PI calls if pi config is false. That way you don't depend only on frontend

**Comment by TheFern2** [comment]
I agree I was thinking about that while making the changes, what would that require? block anywhere where queryOptions.isPiPoint is getting checked if piPointCoinfig is false?

Also on an unrelated question, is there a reason why alerting is false in plugin.json?

**Comment by TheFern2** [comment]
Would this suffice to handle backend?

datasource.ts line 178
```typescript
endTime: options.range.to,
isPiPoint: this.piPointConfig && target.isPiPoint,
scopedVars: options.scopedVars,
```

datasource.ts line 437
```typescript
if (this.piPointConfig && queryOptions.isPiPoint) {
      query.path = this.templateSrv.replace(query.path, queryOptions);
}
```

**Comment by TheFern2** [comment]
@coderReview Can I please get some clarification about what is needed to block PI calls?

**Comment by TheFern2** [comment]
@elwills @StephenCWills @ritchiecarroll @clackner-gpa could someone please clarify my previous question? We would like to use this PR in prod with the signed plugin but if is of no interest to the owner of this repo to pull the request we might just submit our own plugin to the grafana store. I am trying to avoid this of course by making one last communication attempt.

**Comment by clackner-gpa** [comment]
@TheFern2  Give me a few days to look at this. we 'll try to get back to you next week

**Comment by TheFern2** [comment]
> @TheFern2 Give me a few days to look at this. we 'll try to get back to you next week

sound great, thanks for the response.

**Comment by clackner-gpa** [comment]
@TheFern2, Thank you for your work on this. Unfortunately, since this is submitted from your fork I can't comment/ make additional commits, so you will need to make the changes. 
I believer @coderReview was referring to the fact that the changes are hiding the UI in `QueryEditor.tsx` Line 932. However the coresponding setting (`datasource.props.piPointConfig` does not prevent the datasource from quering PI. You should be able to use the `IsPiPoint` and `piPointConfig` settings together to prevent the datasource from making the call to PI in `datasource.ts`

**Comment by TheFern2** [comment]
@clackner-gpa I was typing this as you commented. The allow maintainers is on on this PR, but no worries I can make necessary changes.

https://github.com/GridProtectionAlliance/osisoftpi-grafana/blob/master/src/datasource.ts#L937

```
private restGetWebId(assetPath: string, isPiPoint: boolean): Promise<PiwebapiRsp> {
    var ds = this;
```

I am thinking to make sure the correct boolean is passed based on the admin config and ui toggle pi point, if admin is false, then this will always be false of course.

**Comment by TheFern2** [comment]
@clackner-gpa Okay I made some modifications and I believe this takes care of protecting the backendSrv, lemme know what you think or if you want to go another route. Thanks!

**Comment by coderReview** [comment]
@TheFern2  can you please rebase your PR to this branch `feature/v3.1.0`

**Comment by TheFern2** [comment]
> @TheFern2 can you please rebase your PR to this branch `feature/v3.1.0`

what would that entail? I rarely use rebase.

```
git checkout feature/v3.1.0
git rebase pi-point-option
git push origin feature/v3.1.0
```
I think I would have to submit new PR since this would be on another branch, no?

**Comment by coderReview** [comment]
Sorry. Just change the target branch  to 'feature/v3.1.0'

**Comment by TheFern2** [comment]
done

**Comment by TheFern2** [comment]
@coderReview Thanks for the merge, just for my own reference how often are grafana store releases pushed? Is there a release cadence?

**Comment by clackner-gpa** [comment]
We usually release in coordination with @coderReview to ensure any major changes result in a release. Unless he has any objections we can get a release build started in the next few days.

**Comment by coderReview** [comment]
@TheFern2 v3.1.0 is ready to go. I am preparing v4 which should release new month. Have to do a lot of testing. But I will push the initial commit next week.

This has some breaking changes, but I am adding a compatibilty flag to allow easy migration.

**Comment by TheFern2** [comment]
Ah ok gotcha, thanks for the info, looking forward to the release.

**Pull request merged**
