### PR TITLE
Add feature to query PI points directly

### PR DESCRIPTION
**Pull request by cluffja**
I made as minimal changes as possible to add the capability to query PI points directly from the dataserver. There is an abundance of unused code, much of which appears to have been initially created for this PI point feature. So as to not completely overhaul things I added minimal code to adapt the current solution to add PI point querying. 

I slightly modified the GUI to allow toggling of searching via PI point or AF. In doing so I removed code that was generating a phantom segmentsrv object in the segments path. Perhaps it is necessary for something else? In my testing I didn't notice a change in performance of any features with it removed.

I added some images for explaining the difference between querying via the AF and querying via PI points as well as some documentation on how in the README. 

Let me know your thoughts and if I mucked things up. I performed the grunt build but it's possible I missed thing. I live in Python, not web development.

### CODE REVIEW

**Comment by cluffja** [comment]
Updated to accommodate for the bug when editing panels. Performed more testing. So far, no issues.

**Comment by sonicdoo** [comment]
Dear cluffja, thanks for your great Feature to query PI points directly! It is working very good, except I can not use the "Recorded values" and also the Calculations are not working for me.

Does that work for you?

grafik

**Comment by sonicdoo** [comment]
@cluffja small Update: the Recorded Values are working, when there is also a value for the "Max Recorded Values" entered.
Also regarding the Calculation I can not exclude if the problem depends on the piwebapi I´m using.

Another cool addition would be the possibility to get a list of the available pi-tags in PiPoints mode instead of exactly enter the tag-name. I´m already trying to develop this, unfortunatly I´m not having so much experience in JS to really push this forward.

**Comment by cluffja** [comment]
@sonicdoo well that is good to know in tracking things down. The Recorded Values and Calculation fields I have not used too often for various reasons. 

As for the PiPoint list idea, I agree but I'm also a bit unsure how to go about doing the implementation. Some users have millions and millions of PiPoints (the company I work for does). In this case it would break things if we listed them all. We'd need to figure out either paging or some other method to handle the size.

**Comment by sonicdoo** [comment]
@cluffja you are right, just listing all PiPoints might be not practically due to the amount of PiPoints. I`m thinking about listing all relevant PiPoints which got a entered searchstring inside. And then maybe just show the list when there are max 100 points found. In my case the pi-tagnames are self-explanatory. I think this would interfere the step when the wepapi is asked for the webID.

**Comment by FCCMac** [comment]
I'm testing this out as it's been on my wish list for some time, but I can't seem to get it to find my data server. Is there something I need to configure in the Web API? When I toggle "PI Point Search", the "Data Server" field still shows "Select AF Element" and the AF server is still in the dropdown:

image

**Comment by FCCMac** [comment]
@cluffja No need for an apology, I'm super appreciative of the work you've done so far! I'm going to go through the code tomorrow and see if I can work out what's gone wrong for me. I'll also roll back grafana and try a few previous versions. I'm currently running the docker hub latest tag which is 7.5.6. Which version did you test on? Again, thank you for what you've done so far!

**Comment by sonicdoo** [comment]
I'm using the version based on Grafana v7.4.3 (010f20c1c8) and querying pipoints directly works for me. (no AF-Server available on the piwebapi I´m using)

grafik

nothing special on my datasource config:

grafik

**Comment by cluffja** [comment]
And I was testing/developing on Grafana 7.3.7 (Linux) so it makes me think it isn't a Grafana version issue. Also, my PI Server that I'm testing against has an AF server so whether it's there or not doesn't seem to matter either. I'll keep pondering on this.

**Comment by FCCMac** [comment]
I probably should've done this before commenting, but it looks like it's a browser issue. I thought Grafana was compatible with all Chromium browsers, but Brave seems to not like executing *all* of the JS on a page... It's working fine in Chrome now, but calculations are still an issue. In order to get data, I have to leave the "Calculation" field completely empty.

I've just started looking into it and I'll be sure to report if I see anything that jumps out at me. I'll admit, though, my JavaScript skills are pretty lacking.

**Comment by cluffja** [comment]
Woo! That's fantastic news. I'm a huge fan of Brave. Good to know that it might cause issues.

**Comment by Coding-Mike** [comment]
This is a fantastic enhancement. Is there a plan when this will be merged?

Kind regards
Michael

**Comment by txjmb** [comment]
This patch has been very helpful to us and is an important enhancement.  I would second @Coding-Mike 's question on merging.  Happy to help if I can.  We have tested it quite a bit and it seems to work well.

**Comment by ritchiecarroll** [comment]
I generally let @coderReview merge these as he has an environment where these features can be tested,

That said, I recently have a new PI instance setup as well - but I don't have all the web interfaces and AF configured yet - so I am not able to fully test.

That said, if @coderReview doesn't have time to review, I can merge simply based on your successful deployments.

**Comment by coderReview** [comment]
hi @ritchiecarroll  let me see if I can find this week to check. If not let's go ahead.

**Comment by txjmb** [comment]
Thanks to @coderReview and the rest of the team!  Great work on this plugin.

**Comment by ritchiecarroll** [comment]
@coderReview OK to merge?

**Comment by txjmb** [comment]
Any chance this can be merged?

**Comment by coderReview** [comment]
@cluffja can you fix the PR conflict? I will try to look at this PR this week. Thank you

**Pull request merged**
