### PR TITLE
Fixed annotation query and documentation images

### PR DESCRIPTION
**Pull request by coderReview**
## Annotation

Fixed issues

Added attribute selection

## Documentation images

Added new images using new Grafana version

### CODE REVIEW

**Comment by ritchiecarroll** [comment]
Great work!! Thanks for your help with this Grafana plug-in. We are very appreciative of your efforts - looks like a great add.

**Comment by coderReview** [comment]
I was planning on migrating this to the new plugin structure. But in 1-2 months time.

**Comment by ritchiecarroll** [comment]
Sounds excellent. Also, now that you have write access to this repo, hopefully you can see these new alerts:

https://github.com/GridProtectionAlliance/osisoftpi-grafana/network/alerts

I am hopeful that most of these can be cleared up by simply updating JavaScript libraries to the latest versions, but I am hesitant to do so without a good testing environment. As part of any future work you might do, perhaps this is a task you can review.

Thanks again,
Ritchie

**Comment by coderReview** [comment]
hi @ritchiecarroll I cannot open the above url

**Comment by ritchiecarroll** [comment]
Since I cannot figure out how to grant you rights to this, here you go:
image

**Comment by coderReview** [comment]
still 404. can you open it?

**Comment by ritchiecarroll** [comment]
Yeah I can - I posted image above that is report

**Comment by ritchiecarroll** [comment]
Think I found a user security access setting - can you access now?

**Comment by coderReview** [comment]
yes

**Pull request merged**
