### PR TITLE
Support values with spaces in variable expansion

### PR DESCRIPTION
**Pull request by kristwaa**
When the element/path component represented by a Grafana variable contains spaces the expansion fails, resulting in a query with /{unit 1, unit 2}/ in the path.
Add space to the regex to support names with spaces.
Remove redundant part of regex (the 'i' modifier is used).

### CODE REVIEW

**Comment by coderReview** [comment]
@kristwaa can you please keep only datasource.ts file in the PR? thank you.

**Comment by kristwaa** [comment]
@coderReview , I believe this happened because you changed the target branch.
Do you want to merge this to `master` and cherry-pick the commit to `feature/v4.0.0`, or shall we close this PR? If we close, then I can reimplement the fix targeting the `feature/v4.0.0` branch in a new MR.

**Comment by coderReview** [comment]
You can close this one and open a new against feature/v4.0.0 branch. Also, please don't add `dist` folder to your PR.

**Comment by kristwaa** [comment]
Done. I find it awkward to have `dist` in there in the first place - for several reasons - but there may be historical reasons for that. 

Closing, replaced by #116 .

**Pull request closed without merging**
