### PR TITLE
Add RefId to the Results

### PR DESCRIPTION
**Pull request by mikhail-vl**
@coderReview RefId is required to identify the request. I see you did the same in React's branch. Please approve.

When are you going to release the new version and submit it to the Grafana team for review?

### CODE REVIEW

**Comment by coderReview** [comment]
I am not going to deploy a new version for the old Angular code.

**Comment by mikhailredis** [comment]
@coderReview I understand, when are you planning to finish migration to React?

As a workaround for our project, we modified the code and signed the plugin for private use, but I would like to use the official version when it's ready.

**Comment by casperth** [comment]
Hello, Will you also solve the problems with Expression in the new version?

**Comment by casperth** [comment]
Hi Paulo,

The issue number is 63

Verstuurd vanaf mijn iPhone

**Pull request closed without merging**
