### PR TITLE
Support to new Plugin famework

### PR DESCRIPTION
**Pull request by coderReview**
Support 8.2+ using React plugin template

### CODE REVIEW

**Comment by AndreasFridh** [comment]
Good job! What is the process to upload to Grafana plugin rep? Could I contribute in any way?

**Comment by coderReview** [comment]
> Good job! What is the process to upload to Grafana plugin rep? Could I contribute in any way?

This has to be done by the GridProtectionAlliance team. You can test the plugin and report issues and improvements. Thank you.

**Comment by Coding-Mike** [comment]
Hi, 
great job!
when will this new react based version be available for release in grafana?

**Comment by coderReview** [comment]
We are still working on the process of deploying to Grafana

**Comment by SC-66** [comment]
Hi! I'm really looking forward to the 2.0 release! Any idea of when it will be available?

**Comment by AndreasFridh** [comment]
I have tested this on my system now. 

Hav not found any specific new problmes yet, but annotation seems to be fetching the database at least now. Batch fetching of variable data in queries is still not correctly formated and the API resonds with error.

**Comment by willielee17** [comment]
> I have tested this on my system now.
> 
> Have not found any specific new problems yet, but annotation seems to be fetching the database at least now. Batch fetching of variable data in queries is still not correctly formatted and the API responds with error.

I'm interested in also testing this version.  How do I build the plug-in and add to my Grafana instance?

**Comment by coderReview** [comment]
Get this file https://github.com/GridProtectionAlliance/osisoftpi-grafana/releases/download/v2.0.0-beta/gridprotectionalliance-osisoftpi-datasource.zip.

Unzip in your Grafana plugins folder (default `/var/lib/grafana/plugins`). 

Check here how to allow unsigned plugins - https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

Start grafana server.

**Comment by willielee17** [comment]
> Get this file https://github.com/GridProtectionAlliance/osisoftpi-grafana/releases/download/v2.0.0-beta/gridprotectionalliance-osisoftpi-datasource.zip.
> 
> Unzip in your Grafana plugins folder (default `/var/lib/grafana/plugins`).
> 
> Check here how to allow unsigned plugins - https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins
> 
> Start grafana server.

Thank you, coderReview.  We will try it out!

**Pull request merged**
